name: CodSpeed

on:
  push:
    branches:
      - "main"
  pull_request:
  # `workflow_dispatch` allows CodSpeed to trigger backtest
  # performance analysis in order to generate initial data.
  workflow_dispatch:

jobs:
  benchmarks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Cache Rust installation
        uses: Swatinem/rust-cache@v2

      - name: Install cargo-codspeed (with cache)
        uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-codspeed

      - name: Build the benchmark target(s)
        run: cargo codspeed build -p tfhe --features=boolean,shortint,internal-keycache,seeder_unix boolean-bench

      - name: Run the benchmarks
        uses: CodSpeedHQ/action@v1
        with:
          run: cargo codspeed run
